### ISSUE TITLE
Question: Displaying UniProt feature JSON using Nightingale

### ISSUE THREAD

**Issue by prihoda** [ebi-webcomponents/nightingale#136]
Hi @Swaathik and @xwatkins, 

we are using the old ProtVista viewer and would like to migrate to Nightingale. I wasn't able to find much info on how to display the UniProt API result in Nightingale, essentially to replicate the original ProtVista tracks. Is that possible? Can you point me to some resources?

Thanks!
David

**Comment by xwatkins** [comment]
Hi David, thanks for your message. There are 2 different ways to do this:

## Using the `protvista-uniprot` webcomponent
There is separate repo which provides a Web Component to replicates the "old" ProtVista functionality. It uses the Nightingale components under the hood, and is customisable so you can decide what track(s) to display as well as which APIs to connect to (by default you will get the same as displayed in the UniProt website). 
https://github.com/ebi-webcomponents/protvista-uniprot

There is a codepen here if you want to have a play https://codepen.io/xwatkins/pen/rXpZXX?editors=1000

## Implementing your own view with the Nightingale components
This requires a bit more work but gives you complete control about the way the components look, the data they display and how they interact. However it requires a bit more work from your part.
If you're using a JavaScript framework like React, View etc... you can import the components as modules. Otherwise you can also just use them as regular components.

Here's a codepen https://codepen.io/xwatkins/pen/jOybjbx?editors=1000
and here's the doc on getting started https://ebi-webcomponents.github.io/nightingale/#/

Let me know if any questions, happy to schedule a call if needed.

**Comment by prihoda** [comment]
Thanks @xwatkins, we successfully implemented our viewer inspired by the `protvista-uniprot` component, closing this issue now
