### ISSUE TITLE
Zooming in by double-click

### ISSUE THREAD

**Issue by prihoda** [ebi-webcomponents/nightingale#156]
**Is your feature request related to a problem? Please describe.**
Zooming in using the scrollwheel can be quite slow, could we also zoom in by double clicking?

**Describe the solution you'd like**
I would like to zoom in by doubleclicking anywhere in the view. Also maybe when doubleclicking on a feature, the view could zoom in on that feature (to reveal the feature and parts of the sequence around that feature).

**Describe alternatives you've considered**
Using scrollwheel

@xwatkins is this something you would consider for the public version, or shall we implement this internally in our fork?

**Comment by gustavo-salazar** [comment]
Hey there,
Really sorry we never replied to your reported issue. We are working on a complete rewrite of all the components and hope to have a beta release by November. I'll keep this issue open as a reference to the problem, so it doesn't propagate to the new version. However, it won't be fixed in the current codebase
