### ISSUE TITLE
protvista structure highlight property causing diagram to fade

### ISSUE THREAD

**Issue by rizwan-ishtiaq** [ebi-webcomponents/nightingale#170]
**Describe the bug**
When using protvista-structure (version 3.4.0) with property "highlight" result diagrams are broken

**To Reproduce**
`<protvista-structure accession="Q9NUW8" structureid="6n0d" highlight="493:493" />`

**Expected behavior**
Over all diagram should look same as it would be without highlight property

**Screenshots**
With highlight property
![Screenshot from 2021-10-26 09-57-49](https://user-images.githubusercontent.com/34174422/138845757-624ef6f2-393f-44bd-9be2-dca7bb1cd466.png)
Without higlight property
![Screenshot from 2021-10-26 10-00-14](https://user-images.githubusercontent.com/34174422/138846096-a84629fc-dd45-48fe-a8f8-4ac6f82b97aa.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser Chrome
 - Version Version 94.0.4606.81 (Official Build) (64-bit)

**Comment by gustavo-salazar** [comment]
Hey there,
Really sorry we never replied to your reported issue. We are working on a complete rewrite of all the components and hope to have a beta release by November. I'll keep this issue open as a reference to the problem, so it doesn't propagate to the new version. However, it won't be fixed in the current codebase.
