### ISSUE TITLE
Version 3 Down

### ISSUE THREAD

**Issue by choiwhmarco** [ebi-webcomponents/nightingale#244]
Is nightingale v3 down now? All the documents are unavailable. [V3 Page](https://ebi-webcomponents.github.io/nightingale/v3/)

**Comment by gustavo-salazar** [comment]
Hey @choiwhmarco, thanks for letting us know. 

The automatic deployment failed a couple of days ago and I didn't notice. I have fixed the issue and redeployed it. It should be operational now.

FYI, the cause of the problem was that GH actions updated their default running image and with it, the version of Node. and seems that NIghtingale v3 have issues with v18. It is now set to run with Node v14

Thanks again for reporting the issue.
