### ISSUE TITLE
nightingale-msa fails to build under npm/babel

### ISSUE THREAD

**Issue by DanBuchan** [ebi-webcomponents/nightingale#260]
**Describe the bug**
After using npm install to add @nightingale-elements/nightingale-msa and including it in a react scrip compilation fails with missing function message

```ERROR in ./node_modules/@nightingale-elements/nightingale-msa/dist/index.js 4912:168-240

Module not found: Error: Can't resolve './workers/conservation.worker.ts' in '/home/dbuchan/Code/psipred_react/node_modules/@nightingale-elements/nightingale-msa/dist'```

**To Reproduce**
1. `npm install /@nightingale-elements/nightingale-msa`
2. Add import to react script `import "@nightingale-elements/nightingale-msa";`
3. Run `npm start` or `npm build`

**Expected behavior**
Package is added to build/compiled code to without error

**Desktop (please complete the following information):**
- OS: Rocky 8 and Rocky 9
- npm 9.4.0

**Comment by gustavo-salazar** [comment]
Hey there,
Are you using webpack or rollup?
If using webpack try using `worker-loader`: https://v4.webpack.js.org/loaders/worker-loader/ although apparently since webpack v5, it is not necessary.

For rollup we are using `rollup-plugin-web-worker-loader` https://www.npmjs.com/package/rollup-plugin-web-worker-loader

**Comment by gustavo-salazar** [comment]
OK, after answering this, I notice that the `/dist` files actually don't include the worker.

The examples are using storybook, which uses webpack. The syntax used in the component was written according to webpack examples, and that's why the examples work. However we use rollup to build the packages published in npm, and the syntax for web workers is slightly different in rollup. 

We at InterPro use webpack on our build, and therefore the current component works for us, and never noticed this issue.

I'll work on this issue to make a compatible version and will report here.

Unfortunately,  for the moment the only option to use this package is using webpack to bundle it.

Sorry for the inconvenience, and thanks for reporting it.

**Comment by gustavo-salazar** [comment]
See the PR #262 for the proposed fix on this issue.

I created a working example of the msa in a codepen. You can have a look here: https://codepen.io/gustavo-salazar/pen/ZEmWbLp

Let me know if this solves your problem

**Comment by DanBuchan** [comment]
Hi, thanks for the response. In the end we had implemented a simple alignment viewer before you responded. But if we revisit this next year with our upcoming site refresh I'll take a look.
