### ISSUE TITLE
undefined property handling in  Protvista-manager

### ISSUE THREAD

**Issue by mandarsd** [ebi-webcomponents/nightingale#44]
Please add a check for e.detail.type is defined here
https://github.com/ebi-webcomponents/nightingale/blob/master/packages/protvista-manager/src/protvista-manager.js#L67

The component is binding to native input elements change events which do not have the 'type' property defined

**Comment by gustavo-salazar** [comment]
Hey @mandarsd not sure if this is still a problem... the file has changed since you open the ticket and I think the link is not pointing to the right line. But I worked on something that if the attribute changed is now `null` or `undefined`, then `protvista-manager` removes the attribute from its children instead of setting it as `undefined`. Would that fix the issue?
